added error checking in post processing run script

diff --git a/Tests/PostProcessing_test/runtests b/Tests/PostProcessing_test/runtests
--- a/Tests/PostProcessing_test/runtests
+++ b/Tests/PostProcessing_test/runtests
@@ -1,5 +1,8 @@
-#!/bin/bash
+#!/bin/bash -i
 
-source ~/.bashrc
 python main.py
 visit -nowin -cli -s main.py
+
+if [ $? -eq 127 ]; then
+        echo "visit command not found. Set the 'visit' variable in your bash profile"
+fi
